name: pixabay_viewer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  http: ^1.2.1
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  built_value: ^8.9.2
  built_collection: ^5.1.1
  get_it: ^7.7.0
  injectable: ^2.4.1
  loading_animations: ^2.2.0

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  built_value_generator: ^8.9.2
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true
  generate: true