name: pixabay_viewer
description: "Pixabay Viewer"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  http: ^1.2.1
  equatable: ^2.0.5
  built_value: ^8.9.2
  built_collection: ^5.1.1
  get: ^4.6.6

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  built_value_generator: ^8.9.2

flutter:
  uses-material-design: true
  generate: true